### PR TITLE
docs: Add GlobalX to the list of companies that use Flux

### PR DESCRIPTION
**Pull request by drewfreyling**
Add GlobalX to list of companies that use it.

### CODE REVIEW

**Comment by squaremo** [comment]
I just changed the formatting of the production users table to make it easier for people to add themselves -- I've rebased this PR and made the same change as your original commit (adding GlobalX to the list, in the appropriate place).

I hope that is OK, @drewfreyling, it's a more intrusive rebase than I would normally do :-) Do you mind quickly redoing the DCO sign-off -- reset to this HEAD, then make sure the commit author lines up with the sign-off (not sure if my rebase upset it or whether it was different before). https://github.com/fluxcd/flux/pull/3358/checks?check_run_id=1464731484 has the details and instructions.

**Review by dholbach — APPROVED** [review]
Thanks @squaremo and welcome @drewfreyling to the Flux community!

**Comment by kingdonb** [comment]
@drewfreyling Could you please `pull --rebase main` and sign off this commit for DCO? Then it can be merged. Thanks!

**Comment by dholbach** [comment]
Thanks a lot!

**Pull request merged**
