### PR TITLE
Update readme with new pubsub integration

### PR DESCRIPTION
**Pull request by lsjostro**
Update readme with link to google pubsub integration

### CODE REVIEW

**Comment by dholbach** [comment]
Hey @lsjostro - thanks a lot for the submission and for making Flux talk to other services! This is great.

It looks like your project is still quite young. Do you have any sense how many folks are using it and what the feedback was upon until now? In the "Integrations section" on the Flux README we're looking for well-tested and agreed-upon solutions. That's why I'm asking.

If you're still looking for users and feedback, we're happy to amplify the signal and get you in touch with users. Off the top of my head I would recommend our different Slack(s), our mailing list, Twitter, and our next Flux Dev meeting for this.

Please let us know if we can help with any of this.

**Comment by lsjostro** [comment]
Thanks for the feedback! I'll try to reach out to the community through the other channels! Cheers!

**Comment by dholbach** [comment]
There's
- #flux on the Weaveworks Slack
- #flux on the CNCF Slack
- #gitops on the Kubernetes Slack
- discuss.k8s.io
- the Flux CNCF mailing list
- Twitter

Let us know if you want any Retweets, etc. :-)

**Comment by dholbach** [comment]
@lsjostro Shall we continue the discussion on Slack or somewhere else maybe?

I hope you're not discouraged now.

**Pull request closed without merging**
