### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by cmanzi**
Fixes https://github.com/fluxcd/flux/issues/2806, and partially addresses https://github.com/fluxcd/flux/issues/2812. 

We are heavy users of FluxCD in a multi-tenant environment, and the default logging was not cutting it for us, as mentioned in other issues.

It adds the following flags:
`--log-level` - set the log level for Zap logging output
`--log-devel` - set logging to Zap logging 'development' mode (trace, effectively)

Our solution was to replace the current logger with Zap structured logging (we use JSON, but it still supports `logfmt` by way of a compatibility library). We use JSON logging:
```
{"level":"error","ts":1581636184.4995604,"caller":"cache/warming.go:181","msg":"error requesting tags","component":"warmer","canonical_name":"quay.io/jetstack/cert-manager-controller","error":"error parsing HTTP 429 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>429 Too Many Requests</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>429 Too Many Requests</h1></center>\\r\\n<hr><center>nginx/1.12.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","stacktrace":"github.com/fluxcd/flux/pkg/registry/cache.(*Warmer).warm\n\tgithub.com/fluxcd/flux/pkg/registry/cache/warming.go:181\ngithub.com/fluxcd/flux/pkg/registry/cache.(*Warmer).Loop\n\tgithub.com/fluxcd/flux/pkg/registry/cache/warming.go:124"}
{"level":"error","ts":1581636190.6412482,"caller":"cache/warming.go:181","msg":"error requesting tags","component":"warmer","canonical_name":"quay.io/jetstack/cert-manager-webhook","error":"error parsing HTTP 429 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>429 Too Many Requests</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>429 Too Many Requests</h1></center>\\r\\n<hr><center>nginx/1.12.1</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","stacktrace":"github.com/fluxcd/flux/pkg/registry/cache.(*Warmer).warm\n\tgithub.com/fluxcd/flux/pkg/registry/cache/warming.go:181\ngithub.com/fluxcd/flux/pkg/registry/cache.(*Warmer).Loop\n\tgithub.com/fluxcd/flux/pkg/registry/cache/warming.go:124"}
{"level":"error","ts":1581636242.7061758,"caller":"kubernetes/images.go:39","msg":"error parsing container image","resource":"kube-system:daemonset/node-authorizer","image":"quay.io/gambol99/node-authorizer:v0.0.4@sha256:078b948b8207e43d35885f181713de3d3c0491fe40661d198f9bc00136cff271","error":"expected image name as either <image>:<tag> or just <image>: invalid image ID","errorVerbose":"invalid image ID\ngithub.com/fluxcd/flux/pkg/image.init\n\tgithub.com/fluxcd/flux/pkg/image/image.go:22\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5222\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.main\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:190\nruntime.goexit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/asm_amd64.s:1357\nexpected image name as either <image>:<tag> or just <image>\ngithub.com/fluxcd/flux/pkg/image.init\n\tgithub.com/fluxcd/flux/pkg/image/image.go:24\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5222\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.doInit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:5217\nruntime.main\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:190\nruntime.goexit\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/fluxcd/flux/pkg/cluster/kubernetes.mergeCredentials\n\tgithub.com/fluxcd/flux/pkg/cluster/kubernetes/images.go:39\ngithub.com/fluxcd/flux/pkg/cluster/kubernetes.(*Cluster).ImagesToFetch\n\tgithub.com/fluxcd/flux/pkg/cluster/kubernetes/images.go:177\ngithub.com/fluxcd/flux/pkg/registry.ImageCredsWithAWSAuth.func5\n\tgithub.com/fluxcd/flux/pkg/registry/aws.go:218\ngithub.com/fluxcd/flux/pkg/registry/cache.(*Warmer).Loop\n\tgithub.com/fluxcd/flux/pkg/registry/cache/warming.go:131"}
```

The goal was to improve the log output while changing as little else as possible (I tried to 'interpret' the intended levels where they weren't obvious). Some work was done to 'clean up' the messages, but we kept the content largely the same. 

One part that could not be ported over was the k8s logger (only accepts a go-kit logger), so we used a compatibility package to get a child go-kit logger from our main Zap logger.

### CODE REVIEW

**Comment by squaremo** [comment]
Levelled logging would make me happy :+1: And this is a substantial amount of careful work.

I feel I need to carefully pick my way over each invocation to see if it's an appropriate replacement (and to understand zap's API).

In the meantime, @cmanzi can you comment on these:

 - if people have filters/searches/etc. set up on their logs, to what extent will those still work?
 - what is it (aside from levels) that recommends zap specifically?

Thanks!

**Comment by cmanzi** [comment]
@squaremo 
> * if people have filters/searches/etc. set up on their logs, to what extent will those still work?
That depends on what they are filtering for. If they are filtering for say, `error` then those filters should still work since all error-leveled messages will have `"level": "error"` in them. 

If someone is filtering for error messages (as we were) by filtering negatively for `"err":null`, or vice versa, then it may cause issues due to the `"err":null` no longer being present in info-leveled messages. However, imo non-error messages should not typically have `err` present in them, so I didn't add anything back in to handle this case. 

> * what is it (aside from levels) that recommends zap specifically?

It's a highly performant and well-supported structured logging package. Support for leveled logging is a big win obviously. It has a lot of nice features like a wide range of built-in 'Fields' to build structured logs, as well as customizability with the ObjectMarshaller/ArrayMarshaller interfaces for custom Fields, support for custom log formats (with logfmt, console, and json by default).

**Comment by squaremo** [comment]
I am inclined to try and include this in the next minor release -- what do you think @hiddeco @stefanprodan ?

> One part that could not be ported over was the k8s logger (only accepts a go-kit logger), so we used a compatibility package to get a child go-kit logger from our main Zap logger.

@cmanzi I didn't quite follow what you're saying. Is it the bit here: https://github.com/fluxcd/flux/pull/2851/files#diff-350e484490d6241fa81c13942d160480R310

If so, that logger only appears to be used by the code immediately following, which simply invokes k8slog.Log as an error handler. I reckon just use the normal log and change the invocation.

**Comment by stefanprodan** [comment]
I'm all for replacing go-kit with zap 👍 Does the `logfmt` package formats the logs in the same way go-kit does? My concern is that people have developed log parsers in Fluentd/Logstash and this change could break the parsers.

**Comment by hiddeco** [comment]
I am all-in on leveled logging but have the same concerns as @stefanprodan.

**Comment by cmanzi** [comment]
> If so, that logger only appears to be used by the code immediately following, which simply invokes k8slog.Log as an error handler. I reckon just use the normal log and change the invocation.
@squaremo  I should clarify: when I originally worked on this, I kept the compatibility logger in place because zap does not have an equivalent `Valuer` implementation that I know of. 
However upon further examination, I believe the new changes I just pushed should achieve the same effect.

> Does the logfmt package formats the logs in the same way go-kit does? 
Yes, I tested this out to make sure they look the same.

> My concern is that people have developed log parsers in Fluentd/Logstash and this change could break the parsers.
@stefanprodan Yes I considered this. If people are parsing for `error` or just the content of the messages then that should still work (I tried to not change the log content), but if they were looking for errors by searching for a pattern like `"err":!null`, then those might not work.

We might be able to rectify by setting the `error` level key for zap to `err` instead of `error`, or by adding a field to these messages to ensure it triggers the same parsing...open to suggestions on how to maintain backwards compatibility here.

**Comment by prometherion** [comment]
Please, keep in mind to keep the formatting backward compatible as possible: the `ts` field looks to being converted to a float when at present time it's an _RFC 3339 Nano_ string and would break all the parsing put in place by customers.

If you need help with the PR glad to contribute!

**Comment by cmanzi** [comment]
@prometherion Ok I changed the logging encoder to use RFC 3339 Nano.

@stefanprodan @squaremo @hiddeco Regarding the backwards compatibility - I modified the error field in error messages to use a key of `err` instead of `error` to conform to the previous format for error messages. This way, if someone is filtering for `err` or `error` they should still pick up the error logs as both will be present. This should also cover cases of parsing for `"err": !=null`.

Please let me know if you think of any other cases where this might break backwards-compatibility.

**Comment by cmanzi** [comment]
Not sure what exactly is failing in the 'link-checker' tests - ` Fail if there were link errors`. Can anyone help me to understand this so I can fix it?

**Comment by hiddeco** [comment]
@cmanzi I think this has been fixed in `master` and rebasing the PR on top of this should resolve the issue.

**Comment by cmanzi** [comment]
@hiddeco Thanks! that did it

**Comment by withnale** [comment]
Is there any movement on this card? Not having log messages of a well defined severity makes tracking problems much more painful than it should be.

**Comment by fllaca** [comment]
Looks like another rebase is needed, there are some little conflicts with master. At my company we would be also very interested in this enhancement, currently is not very easy for us to handle Flux logs when using the json format.

**Comment by cmanzi** [comment]
@hiddeco any chance this will be looked at soon? I probably won't have a lot of time in the near future to rebase/maintain this branch.

**Comment by joostschriek** [comment]
@cmanzi If you need any help with keeping this up to date i'm happy to help. We've just run into a bunch of logging issues because of `everything is considered an error` cloud logging :upside_down_face:

**Comment by nlloyd-invitae** [comment]
Taking over from @cmanzi on this one. Rebased against master.

**Comment by nlloyd-invitae** [comment]
@hiddeco @stefanprodan any chance we can get this reviewed soon?

**Comment by squaremo** [comment]
I'll include this in the next minor version release, with a caveat in the release notes:

> NB This changes the logging package used. Care has been taken to produce logs that will work with existing log analysis; however, if you depend on scanning Flux logs, it is worth reviewing that configuration. See https://github.com/fluxcd/flux/pull/2851 for details of the changes.

Looks like I don't have write access to the fork, so I can't rebase this. Can someone either check that box (I can't remember exactly where it is), or rebase and leave out the last few commits that deal with timeouts. Thanks!

**Comment by kingdonb** [comment]
It seems unlikely this can be merged into Flux v1 now (or soon), since changes to the logging output or log structures will represent a breaking change for users that have scripted consumers of the log output, which is really a lot of users.

As Flux v1 is in maintenance mode, do we still see any possibility including this improvement?

**Comment by kingdonb** [comment]
Thank you for your contribution. My understanding after talking it over with the maintainers is that: yes, even improvements to the logging structure will be considered a breaking change in Flux v1, since downstream automation providers may have built integrations that depend on the structure of the logs. Flux v1 in maintenance mode can only consider non-breaking changes for releases in the maintenance period.

As some time has passed since this was submitted and there has been no follow-up for a while, I think it's safe to close.

**Pull request closed without merging**
