### PR TITLE
Add read-the-docs support

### PR DESCRIPTION
**Pull request by dholbach**
After talking to @stefanprodan I realised that versioned docs won't work easily with Gitbook, we'd also just have one free repo.

read-the-docs might be the way to go. Here's a WIP PR to get this into shape.

To run this, do:
```sh
# in top-level directory
make serve-docs
```

### Content
- [x] fix index
- [x] use fonts we use in other places
- [x] break up docs into subdirectories
- [x] solve issues around over-flowing text boxes
- [x] find solution for [bla.md#anchor] links (https://github.com/rtfd/recommonmark/issues/8)
- [x] find solution for links in tables (https://github.com/ryanfox/sphinx-markdown-tables/issues/18)
- [x] Remove the "next read ..." mention in the docs - this is in the RTD UI already
- [ ] factor in [Hidde's feedback](https://github.com/weaveworks/flux/pull/2152#issuecomment-502773997)
- [ ] Helm Operator docs should be in a separate dir
- [ ] fix references from Weaveworks website

### Build
- [x] integrate https://hub.docker.com/r/ddidier/sphinx-doc/
- [x] add linkchecker to find broken links
- [x] hook up `make test-docs` with CI
- [ ] generally document how to use this
- [x] hook up with release/build process (what do we need here? document how to publish a new release branch in readthedocs?)

### Publish
- [x] decide on project-name to use with readthedocs.io
- [x] set up readthedocs.io account
- [ ] publish master
- [ ] pull in older releases
- [ ] link to docs from main README.md

### CODE REVIEW

**Comment by dholbach** [comment]
Screenshot from 2019-06-12 17-54-46

**Comment by dholbach** [comment]
In https://github.com/weaveworks/flux/pull/2152/commits/e3f3730378576b4c2a43b1cef44d4f104498897e I made some changes to set up a new directory/index structure. This is just a proposal for everyone to get an idea. Let me know what you think.

**Comment by dholbach** [comment]
@stefanprodan in 2a30963 I added the build-in/serve-from docker, it's a bit messy, but there's instructions on how to to it in `site/Dockerfile`. Feedback/fixes welcome.

**Comment by stefanprodan** [comment]
@dholbach I've simplified the docs preview, all you need to do is run `make run-docs` from the root of the project.

Running `make run-docs` will:
- build the docs website inside the docker image
- create a docker image named flux-docs:latest
- run the docs website on http://localhost:8000/_build/html/index.html

PS. You can change the port binding with `DOCS_PORT=8080 make run-docs`

**Comment by dholbach** [comment]
Nice work, @stefanprodan! Would it make sense to have `generate-docs` and `serve-docs` targets? How are we going to deploy this?

**Comment by dholbach** [comment]
I just changed the directory structure somewhat... please let me know if I was jumping the :shark: here:

```
.
├── development
│   ├── building.md
│   └── get-started-developing.md
├── faq.md
├── helm
│   ├── helm-integration.md
│   ├── helm-operator.md
│   └── helm-upgrading-to-beta.md
├── how-it-works.md
├── install
│   ├── get-started.md
│   ├── helm-get-started.md
│   ├── installing.md
│   └── standalone-setup.md
├── internals
│   ├── daemon.md
│   ├── fluxyaml-config-files.md
│   └── garbagecollection.md
├── introduction.md
├── requirements.md
├── troubleshooting.md
└── using
    ├── annotations-tutorial.md
    ├── fluxctl.md
    ├── git-gpg.md
    ├── monitoring.md
    └── upgrading-to-1.0.md
```

**Comment by stefanprodan** [comment]
@dholbach as describe here https://dont-be-afraid-to-commit.readthedocs.io/en/latest/documentation.html#readthedocs-org Read the Docs will watch your GitHub project, and build, render and host your documents for you automatically.

**Comment by hiddeco** [comment]
Would it be an idea to split the FAQ (`fluxd` / Helm op)?

**Comment by stefanprodan** [comment]
The docs structure looks ok to me 💯

**Comment by stefanprodan** [comment]
Yeah maybe the Helm Operator docs should be in a separate dir, this would make things easier when we'll have helm-op in its own repo.

**Comment by dholbach** [comment]
You guys think ahead! :+1:

**Comment by hiddeco** [comment]
@dholbach I am going to file my final judgement of the new structure as soon as I have viewed a rendered version of the documentation. Hope to do this by the end of the day :crossed_fingers:

**Comment by dholbach** [comment]
@hiddeco Luckily @stefanprodan made this very easy.... `make run-docs` and you're all set.

**Comment by hiddeco** [comment]
Thoughts now that I have seen the rendered views:

- 'Installing Flux' index should contain a section about installing Flux and the Helm operator at the same time, this could be on a new page or we can divide the 'get started' in two sections, one without the operator and one with.
- I think we should rethink some of the page titles, e.g. we have a top item 'Using Flux' with a 'child page' 'Using Weave Flux'.
- I think we should rethink some parts of the (naming of the) new structure, e.g, we have a 'introducing Weave Flux' index, but also a 'how Weave Flux Works' index. As a new user, I would expect the introduction to contain the latter, so we may need to rethink the naming, or merge parts.
- 'Internals' is something that would scare me away as a user, listing the more important features under this index (garbage collection and manifest factorization) will probably reduce the amount of people finding this information by themselves.
- ...more TBA (this is the result of a couple of minutes of thinking)

I think, to give people the best document experience possible, we should maybe think out a structure without looking at what we currently have, but what we do want to tell people, and merge / rewrite things back into this structure so we revise all documentation at the same time.

**Comment by dholbach** [comment]
https://github.com/rtfd/recommonmark/issues/8 bites us for the following links:
```
faq.md:arguments reference](daemon.md#flags).
faq.md:[standalone-setup.md](./standalone-setup.md#using-a-private-git-host).
helm/helm-integration.md:You can use the [same annotations](./fluxctl.md#using-annotations) in
troubleshooting.md:[FAQ](./faq.md#can-i-change-the-namespace-flux-puts-things-in-by-default).
troubleshooting.md:   [./standalone-setup.md](./install/standalone-setup.md#using-a-private-git-host).
using/annotations-tutorial.md:it. `fluxctl` has the [`--k8s-fwd-ns <NAMESPACE>` option](../fluxctl.md#Connectingfluxctltothedaemon) for specifying the right
using/annotations-tutorial.md:interact with the deployments. First, please [install fluxctl](../fluxctl.md#installing-fluxctl).
using/fluxctl.md:- [`org.opencontainers.image.created`](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys)
using/fluxctl.md:using `flux.weave.works/ignore: "true"`. Read more about this in the [FAQ](faq.md#can-i-temporarily-make-flux-ignore-a-deployment).
```

**Comment by dholbach** [comment]
Screenshot from 2019-06-18 10-19-28

We also need to find a solution for overflowing text boxes.

**Comment by squaremo** [comment]
This is marvellous work, thank you @dholbach, and @stefanprodan and @hiddeco for pushing it onward.

**Comment by stefanprodan** [comment]
@dholbach regarding overflowing text boxes, I think we should use multi-line code blocks and we'll get a horizontal scrollbar.

**Comment by dholbach** [comment]
If we want to hook this up with readthedocs.org and serve the files from there, we need to decide on a project name - [`flux` is taken](https://flux.readthedocs.io/).

**Comment by dholbach** [comment]
@bia Can you remind me of which fonts to use?

**Comment by bia** [comment]
Proxima Nova and Roboto Mono

**Comment by dholbach** [comment]
> Proxima Nova and Roboto Mono

For monospace, right? In this order? Which other fonts to fall back to?

Which general font?

**Comment by bia** [comment]
```
body {
  font-family: "Montserrat", sans-serif;
  src: url(../static/fonts/montserrat-regular.ttf) format("truetype");
}

code {
  font-family: "Roboto Mono", monospace;
  src: url(../static/fonts/robotomono-regular.ttf) format("truetype");
}
```

**Comment by dholbach** [comment]
Some links are also broken because of https://github.com/ryanfox/sphinx-markdown-tables/issues/18 ...

**Comment by stefanprodan** [comment]
@dholbach maybe remove the links from tables? I don't think those are so important. Also I would setup readthedocs.org with `weave-flux` just for testing.

**Comment by dholbach** [comment]
@stefanprodan @hiddeco @squaremo I'd appreciate if you could take a look at the TODO list at the very top and give feedback on what we want to solve now and what can happen later.

While it'd be great to solve all the problems we have with docs in this PR, I'd prefer to get something out soon. :-D

**Comment by dholbach** [comment]
Not sure if `weave-flux` is future-proof considering the discussions about CNCF Sandbox - it should definitely be OK for testing.

**Comment by hiddeco** [comment]
@dholbach none of my feedback is blocking. I think we should deal with the last two items in the content section (as they break the docs), hook-up the test to the CI, and publish it, and continue iterating over what's published.

**Comment by dholbach** [comment]
I worked around the link issues, the `linkchecker` run passes now. I added it to our CircleCI config.

**Comment by dholbach** [comment]
Are these the next steps?

 1. Add master build on readthedocs.io
 1. Link to it from main README.md.
 1. (Check if there are other links which need to be updated.)
 1. Merge this PR.
 1. File issues for all the other bits identified during this work
 1. Celebrate! :champagne: :fireworks: :beach_umbrella:

**Comment by dholbach** [comment]
So regarding readthedocs.io:

- settle on readthedocs ID
- use githubbot account (which?)
- connect the two sites
- push branch to new org(?)
- do we link to master docs by default?
- ...

**Comment by stefanprodan** [comment]
@dholbach 

* settle on readthedocs ID: I would go with `fluxcd` like the org name
* use githubbot account: I think this one `Github Weaveworksbot` see 1Pass
* do we link to master docs by default: yes until the next release when we could switch to it as default

**Comment by dholbach** [comment]
Not sure Flux will need its own Github bot account in the future?

**Comment by stefanprodan** [comment]
yeap, we have to create a bot account in fluxcd org

**Comment by dholbach** [comment]
Has the bot been created?

**Comment by hiddeco** [comment]
@dholbach how does the versioned documenting work, do you know this?

**Comment by dholbach** [comment]
We can have read-the-docs import different branches regarding versions. Stable and Latest are aliases we can assign. We can probably add more aliases too.

**Pull request merged**
