### PR TITLE
Test on Kubernetes 1.22.0

### PR DESCRIPTION
**Pull request by kingdonb**
According to

* https://github.com/kubernetes-sigs/kind/pull/2406

the `kubernetes-sigs/kind` is already prepared to support Kubernetes 1.22.0. Let's test!

### CODE REVIEW

**Comment by kingdonb** [comment]
Shown to be passing in bac1220713b7cc28c3fad3eeaac0b7a7492ada4e 🎉 

(Rearranging / cleaning up some commits for the final merge)

**Comment by kingdonb** [comment]
These changes will make CI pass again, the failure is related to Helm finally closing down their Google Storage buckets, so the Helm v2 "tiller install" test is failing. These tests run against Kubernetes v1.22.0 on the latest `kindest/node` image available as of now.

**Review by dholbach — APPROVED** [review]
This LGTM.

(Not sure if there's any other occurrences of k8s/go versions which would need updating.)

**Comment by kingdonb** [comment]
@dholbach There are. I will bump #3515 for review next, thanks for the LGTM 👍

**Pull request merged**
