### PR TITLE
perf: set sync-timeout

### LINKED ISSUE #3278: consistent timeout on fluxctl sync or fluxctl release (No way to debug)
Is there a standard way to debug a flux release or sync timeout message?  Flux has been working for more than a year and now fluxctl sync and fluxctl release consitently time out.  increasing the timeout to 10 minutes has the same outcome.  verbose flags show no extra information. This is on latest flux release.  Logs show no errors or warnings...  Where should be looking to dig deeper into the cause?  it's driving me crazy.

```
$ helm ls -n flux
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
flux            flux            8               2020-09-03 13:07:10.5118373 -0700 PDT   deployed        flux-1.5.0              1.20.2
helm-operator   flux            6               2020-08-11 23:16:01.8447855 -0700 PDT   deployed        helm-operator-1.2.0     1.2.0
$ fluxctl release --dry-run --update-all-images --all
Submitting dry-run release ...
WORKLOAD                STATUS   UPDATES
staging:deployment/aps  success  aps: 121989234971.dkr.ecr.us-west-2.amazonaws.com/kube-platform:stg-71fead0 -> stg-1659ed5
 ~ 
$ fluxctl release --update-all-images --all
Submitting release ...
Error: timeout
Run 'fluxctl release --help' for usage.
```

**Expected behavior**

A useful message of the source of failure somewhere.

**Logs**

```
ts=2020-09-03T23:36:25.026086631Z caller=warming.go:206 component=warmer updated=121989234971.dkr.ecr.us-west-2.amazonaws.com/kube-activities successful=1 attempted=1
ts=2020-09-03T23:36:25.165516072Z caller=warming.go:198 component=warmer info="refreshing image" image=121989234971.dkr.ecr.us-west-2.amazonaws.com/kube-platform tag_count=37 to_update=1 of_which_refresh=1 of_which_missing=0
ts=2020-09-03T23:36:25.297228321Z caller=warming.go:206 component=warmer updated=121989234971.dkr.ecr.us-west-2.amazonaws.com/kube-platform successful=1 attempted=1
ts=2020-09-03T23:37:30.297215071Z caller=warming.go:198 component=warmer info="refreshing image" image=121989234971.dkr.ecr.us-west-2.amazonaws.com/kube-platform tag_count=37 to_update=1 of_which_refresh=1 of_which_missing=0
ts=2020-09-03T23:37:30.456804492Z caller=warming.go:206 component=warmer updated=121989234971.dkr.ecr.us-west-2.amazonaws.com/kube-platform successful=1 attempted=1
```

**Additional context**

- Flux version: 1.20.1 and 1.20.2
- Kubernetes version: 1.18.6
- Git provider: github
- Container registry provider: aws ecr

### PR DESCRIPTION
**Pull request by jumpeiMano**
Edit: Resolves #3278

I modified `sync.go` to use `SyncTimeout` in `Daemon.Sync` function.
Because sometimes I have saw errors like this.
```
caller=loop.go:108 component=sync-loop err="loading resources from repo: 
error executing generator command \"kustomize build .\" from file \".flux.yaml\": context deadline exceeded
error output:
generated output:\n"
```

### CODE REVIEW

**Comment by jumpeiMano** [comment]
@squaremo @stefanprodan Cloud you please check this PR? 🙇

**Comment by yebyen** [comment]
Hi @jumpeiMano I wonder if you can elaborate on why this change is needed? I see you've provided some context already.

What is timing out, or is there a point at which the timeout was not being honored that this change fixes? How does this fix it? Could we add a test that shows how it was failing before, or can we give some explanation for why this change is needed?

Flux v1 is in maintenance mode, but I'm sure if this fixes something important it can be included in a next release soon!

**Comment by jumpeiMano** [comment]
@yebyen Thank you for your comment!

>why this change is needed?

I am using the patchUpdated feature of flux v1. The command I have written in the .flux.yaml is blow:
```
ls -d */ | xargs -I % sh -c 'echo ---; kustomize build %;'
```
This `kustomize build` command's result is sometimes huge. Often, there is a timeout error here, as described in the [description](https://github.com/fluxcd/flux/pull/3381#issue-533635375).

In flux v1, there are some timeout-related flags, like `git-timeout` and `sync-timeout`, but neither of these flags are applied to this command execution, and the default context created by [`context.Background()`](https://github.com/fluxcd/flux/blob/34c3f2f5acfdbb197a3783b3cfd1dfab66a1ecc0/pkg/daemon/loop.go#L103) is used, I have no way to extend the timeout value. Therefore, I have now made a fix so that the `sync-timeout` value is adopted in the `Sync()` function.

**Comment by kingdonb** [comment]
Hi, I'd really like to include this in 1.22.0 if it solves some weird timeout situations.

Can you add your `--sign-off` to the commit with

```
git commit --amend --signoff
```

and

```
git push --force-with-lease origin set-sync-timeout
```

per the details posted through DCO bot in the checks?

No need to rebase, as I will rebase anyway into #3442,
I should be able to force push into this branch, (but I cannot add your sign-off.)

**Comment by jumpeiMano** [comment]
@kingdonb Thank you for your reviewing! Done!! https://github.com/fluxcd/flux/pull/3381/commits/d0ff2666ca472e364acdac4feeecdc0e4341b9de

**Comment by yebyen** [comment]
I think this resolves #3372 

We should be able to test and close both of these in Flux 1.23.0, it may turn out to take a couple of weeks more, past the milestone assigned date though.

**Comment by kingdonb** [comment]
I'm planning on merging this right after #3250 and cutting a release 1.22.2 that will include this change today.

**Review by kingdonb — APPROVED** [review]
LGTM

**Comment by kingdonb** [comment]
This PR may have caused an issue that is reported in #3500 

If there is any insight you can provide, or an updated/different PR that does not cause the reported ephemeral storage growth issue (unbounded) when timeout is engaging, it would be preferable to fix forward than to simply revert the PR.

@jumpeiMano Do you mind taking a look at this issue, and letting me know if you can confirm the details reported there?

**Pull request merged**
