### PR TITLE
Good example on managing MySQL on k8s with Flux

### PR DESCRIPTION
**Pull request by spron-in**

### CODE REVIEW

**Comment by kingdonb** [comment]
Thanks for submitting this!

I was just working on KubeDB myself (for MySQL/MariaDB even) only last week and felt like my knowledge in this area, managing databases with GitOps, was still a bit lacking. I would like to use a tool with a bit more full-featured than the KubeDB community advertises, (for starters, backups are apparently gated behind the Enterprise license since the last time I used KubeDB), and anyway Percona Operator looks like it might be just what I was looking for!

It looks like this might be a little out of place as it is not a GitHub link, and the other integrations listed in this place all are. I don't know if this is permissively licensed, or if the Percona Operator is a commercial tool – that's my next question.

I found this: https://github.com/percona/percona-xtradb-cluster-operator

It looks like it's Apache 2.0 licensed ✅

Is this your project? Bravo, I'll check it out.

**Comment by kingdonb** [comment]
I can get it merged, but Flux v1 which this repo belongs to is not really in active development anymore; if you want to get more eyes on it then we should find a place to advertise it that Flux v2 users will be more likely to check.

If you can address the failing merge check for DCO bot, I'll be glad to get it merged in, as long as there are no objections from the maintainers.

**Comment by kingdonb** [comment]
Please check the instructions behind the DCO failure's link: https://github.com/fluxcd/flux/pull/3503/checks?check_run_id=3046188458

I cannot merge any PR without a DCO, we just need you to amend your commit with the `--sign-off` flag passed to git.

The other failure that we will see is in CI (and is obviously not related to/caused by any change in your PR)

**Comment by kingdonb** [comment]
@spron-in Hello, are you able to take a look at the DCO failure and resolve it with a `--sign-off`?

I'm working on resolving the (unrelated) e2e-testing issue, so that'll be the only pipeline failure that will hold up merging.

**Comment by spron-in** [comment]
Hello @kingdonb , sorry for not coming back earlier. Did the push just now.

**Comment by spron-in** [comment]
> Thanks for submitting this!
> 
> I was just working on KubeDB myself (for MySQL/MariaDB even) only last week and felt like my knowledge in this area, managing databases with GitOps, was still a bit lacking. I would like to use a tool with a bit more full-featured than the KubeDB community advertises, (for starters, backups are apparently gated behind the Enterprise license since the last time I used KubeDB), and anyway Percona Operator looks like it might be just what I was looking for!
> 
> It looks like this might be a little out of place as it is not a GitHub link, and the other integrations listed in this place all are. I don't know if this is permissively licensed, or if the Percona Operator is a commercial tool – that's my next question.
> 
> I found this: https://github.com/percona/percona-xtradb-cluster-operator
> 
> It looks like it's Apache 2.0 licensed ✅
> 
> Is this your project? Bravo, I'll check it out.

I work at Percona, yeah. We are fully open-source.
Also I have a Github link, but it just points to the blog post: https://github.com/spron-in/blog-data/tree/master/gitops-mysql

I just don't want to duplicate the text in the blog and GH :)

As for the Operator - let me know how can I help :)
We also have great Operator for MongoDB - enterprise-grade and open-source as well: https://github.com/percona/percona-server-mongodb-operator/

**Comment by kingdonb** [comment]
As I mentioned before, it would be good to submit this somewhere that Flux v2 users can find it.

Have you had a look in the website or community repo to see if there's a place where you think it belongs?

I can bring it up when maintainers are back from their vacations so we can get consensus about whether this can be merged here, but I have a feeling they will consider it as low priority since Flux v1 and Helm Operator repos will likely be archived soon.

(No word on how soon exactly...)

**Comment by spron-in** [comment]
@kingdonb yeah, I will check Flux v2 repo then. Thank you. Will close the PR  :)
Let me know if there is anything I can help with regarding DB operators.

**Pull request closed without merging**
