### PR TITLE
feat(digest) Parse images digest

### LINKED ISSUE #885: Handle image names with an image digest instead of a tag
An image name like [this](https://github.com/mithrandi/my-kube/blob/f2ae9ed11b56c91de4887ffa6cba177ad8ae33c6/manifests/kcm/deployment.yaml#L20): `gcr.io/decisive-cinema-167507/kube-cert-manager@sha256:4e79e70added5a2e95fb10bf9a63e4234395a3e047c9bf6a6c1131c383c9f04a`

Will cause an error like this:
```
ts=2017-12-22T15:43:30.33587349Z caller=warming.go:154 component=warmer err="requesting tags: mux: variable \"decisive-cinema-167507/kube-cert-manager@sha256\" doesn't match, expected \"^(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\\\\.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?$\""
```

This can probably be fixed by just adding more craziness to the regex, although it'll take me a little while to comprehend what is already there.

### PR DESCRIPTION
**Pull request by carlosjgp**
In some occasions the same tag can be assigned to different images.
Like for example the official Python images tagged with `3.7` or other
projects which may not have a labeling strategy which only uses a label
like `latest` or `master`. Using digests instead of labels ensures that
you don't receive unexpected upgrades

More info about tags and digests can be found
[here](https://success.docker.com/article/images-tagging-vs-digests)
Fixes #885

### CODE REVIEW

**Comment by squaremo** [comment]
Great, thank you. Can you say a bit about how this change interacts with image updates? Or is it more or less invisible, _except_ in that it avoids errors when parsing image refs that include digests.

**Comment by carlosjgp** [comment]
@squaremo I haven't checked the image updated but, in my opinion, when someone uses a digest instead of a label or in conjunction with a label the intention is to not receive unexpected updates.

I'll create some test to ensure that what I just said is true.

**Comment by carlosjgp** [comment]
@squaremo It took me quite a lot to figure out how to test the automated updates but I think I got it.

I've created a couple of tests to ensure that updates ignore Images with digests since they are supposed to be used when you don't want to receive updates.

**Comment by hiddeco** [comment]
@carlosjgp just wanted to let you know that we haven't forgotten about this PR and that I will likely be reviewing (and testing) this next Monday.

**Comment by hiddeco** [comment]
@carlosjgp gave it a test drive and noticed pretty soon that images from workloads in Kubernetes aren't parsed correctly.

Workloads used for testing:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-digest
  labels:
    app: nginx-digest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-digest
  template:
    metadata:
      labels:
        app: nginx-digest
    spec:
      containers:
      - name: nginx
        image: nginx@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451
        ports:
        - containerPort: 80
```


Take for example `fluxctl <list-workload|list-images>`:

```sh
❯ fluxctl list-workloads
WORKLOAD                               CONTAINER           IMAGE                                                                                                                                                  RELEASE  POLICY
default:deployment/flux                flux                fluxcd/flux:latest                                                                                                                                     ready    
default:deployment/flux-helm-operator  flux-helm-operator  fluxcd/helm-operator:latest                                                                                                                            ready    
default:deployment/memcached           memcached           memcached:1.5.15                                                                                                                                       ready    
default:deployment/nginx               nginx               nginx:1.7.9                                                                                                                                            ready    
default:deployment/nginx-digest        nginx               nginx@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451  ready    
```

```
❯ fluxctl list-images -w default:deployment/nginx-digest
WORKLOAD                         CONTAINER  IMAGE                                                                                                                                                  CREATED
default:deployment/nginx-digest  nginx      nginx@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451  image data not available
                                            '-> (untagged)                                                                                                                                         ?
```

and from the logs:

```
ts=2019-08-05T12:31:41.406348903Z caller=warming.go:180 component=warmer canonical_name=index.docker.io/library/nginx@sha256 auth={map[]} err="requesting tags: mux: variable \"library/nginx@sha256\" doesn't match, expected \"^(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\\\\.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?$\""
ts=2019-08-05T12:32:38.562774778Z caller=warming.go:180 component=warmer canonical_name=index.docker.io/library/nginx@sha256 auth={map[]} err="requesting tags: mux: variable \"library/nginx@sha256\" doesn't match, expected \"^(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\\\\.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?$\""
```

**Comment by carlosjgp** [comment]
Thanks @hiddeco I'll create more tests to cover these scenarios and amend the code accordingly

**Comment by carlosjgp** [comment]
Hi @fabstu ,
I just stopped using flux in favour of ArgoCD. And the fact that this changes did pass the automated tests but not some manual tests it made the work much harder and the feedback not as fast I would like.

I like contributing to open source projects but this was not an ideal experience

Sorry I didn't got this finished, please feel free to fork my branch and finish the work

**Pull request closed without merging**
