### PR TITLE
Update ratchet revision right after successful sync

### LINKED ISSUE #2963: Flux appears unable to proceed when connected for event emission and that fails
**Describe the bug**

We have our flux daemon connected to a local fluxcloud instance which is setup to post to both slack and a webhook.  When fluxcloud is unable to complete one of those things it gives the flux daemon a 500 error and this causes flux to stop proceeding the constantly retry the same commit over and over and over.  In out specific case the slack payload was working but the webhook was throwing a 500.  This caused flux from moving forward in our git history and retrying (succeessfully) to apply the same commit over and over and over.

**To Reproduce**

Deploy flux with fluxcloud and setup a webhook in flux cloud to something that will return a 500.  This will prevent flux from moving forward.

**Expected behavior**

It seems like the event emission aspect of flux should be "fire and forget" and if the downstream event handler doesn't do something properly it shouldn't block flux from moving forward.

**Logs**

```
ts=2020-04-02T15:41:28.486961895Z caller=sync.go:393 component=daemon err="executing HTTP request: 500 Internal Server Error Could not post to Webhook, status: 500\n"
fluxcloud Could not post to Webhook, status: 500 Internal Server Error
```

**Additional context**

- Flux version: 1.18
- Kubernetes version: 1.11
- Git provider: Github

### PR DESCRIPTION
**Pull request by hiddeco**
Fixes #2963, #2984

### CODE REVIEW

**Comment by squaremo** [comment]
Not moving the high water mark when the event fails to be posted isn't a bug, it's the design. That is exactly what the high water mark marks -- the last event that was sent successfully.

**Comment by hiddeco** [comment]
Can you elaborate a bit on why this is the design? I would think the fact that it has been successfully applied on the cluster is what counts (as do the users who filed the issues), and not the fact that we have informed a 3rd party this has happened.

**Comment by squaremo** [comment]
> Can you elaborate a bit on why this is the design?

The idea is to keep track of the point to which you have successfully notified about events. If it were moved before even trying to post an event, then you would lose events. This is an "at least once" design -- each event will be posted once, and maybe more if there are failures.

NB the high water mark is all about the events. Syncing always syncs to the HEAD of whichever branch.

You can argue (as Kyle does I think) that events should be "fire and forget" (or "at _most_ once"). But that's a different _design_, not a bug. A better way to avoid repeated notifications would be to deduplicate at the event receiver (i.e., fluxcloud). And if people still wanted at most once notifications, it'd be reasonable to add that behind a flag, I think.

**Comment by rocktavious** [comment]
I would argue that the communication of what the "git tag" on the repository's meaning is not clear then.  Also as an enduser keeping track of the point to which a successful event is notified feels like a terrible design as the import job that flux does is keep the cluster in-sync with the state of the git repo.  The fact that a notification event didn't submit correctly feels like its not really part of the core functionality that flux serves.  I'd much rather have a metric tracking when failed event notifications happen so i can choose to alert on that or not.  Checking out the where the git tag is is much much more helpful indicator of where all my k8s clusters flux are at.  Specifically we run over 12 flux's and being able to do a git fetch on the tags and see where they are in the git history is a quick troubleshooting indicator that something is amiss.  When this is held up by event notifications its very misleading.

So if this truely is the route to be stayed with for the git tags then i think it needs to be HIGHLY communicated that the git tag's purpose is this (and i would bet most flux users do not know this or think otherwise)

**Pull request closed without merging**
