### PR TITLE
Make clear dockercfg.secretName and configFileName

### PR DESCRIPTION
**Pull request by sebastianortizs4n**
This patches tries to make clear the documentation of how the custom dockercfg via secret works.

### CODE REVIEW

**Comment by sebastianortizs4n** [comment]
I haven't changed any links... looks like the check is not working right.

**Comment by stefanprodan** [comment]
@dholbach can you please look at why the link checker is failing on all PR?

**Comment by dholbach** [comment]
→ https://github.com/kubernetes/minikube/blob/master/docs/addons.md 404
It's in the logs!

Will send a PR.

**Comment by stefanprodan** [comment]
@dholbach I see no logs here:
Screenshot 2020-04-14 at 13 13 10

**Comment by dholbach** [comment]
Try the step before.

**Comment by dholbach** [comment]
@stefanprodan https://github.com/fluxcd/flux/pull/3000

**Comment by dholbach** [comment]
It should be fixed in master. If you rebase now, it should be fine. Looks like some links of the minikube docs changed. :man_shrugging:

**Pull request merged**
