### PR TITLE
WIP: update sops to 3.6.0

### LINKED ISSUE #3186: Using SOPS Sync to Apply takes over 600 seconds to run
**Describe the bug**

I am using SOPS with Flux and it takes about 5 minutes from the time the daemon says it's "trying to sync git changes to the cluster" to when the "sync" apply is logged.

**To Reproduce**

I am using AWS KMS with SOPS, I have 7 secrets. 

Decrypting locally takes 1 second per secret, decrypting in the flux container takes about 1 second per secret, yet when flux runs and uses SOPS it is taking over 600 seconds.

**Expected behavior**

**Logs**

It takes 600+ seconds to sync 7 secrets? 

```
ts=2020-07-09T22:57:59.978015617Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old=1f65bff30457753268cb055e97c0e97f2aa13084 new=1f65bff30457753268cb055e97c0e97f2aa13084
ts=2020-07-09T23:02:51.230198126Z caller=sync.go:539 method=Sync cmd=apply args= count=7
ts=2020-07-09T23:02:51.892497125Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=662.221356ms 
```
**Additional context**

- Flux version: 1.19.0
- Kubernetes version: 1.17.6
- Git provider: GitLab
- Container registry provider: Docker.io

### PR DESCRIPTION
**Pull request by ekristen**
Unsure if this totally solves the GPG issue, still testing. 

Was hoping that this would resolve the following issue but it does not. #3186

### CODE REVIEW

**Comment by via-jordan-sokolic** [comment]
Don't we also need to update the version in `docker/sops.version`?
```diff
- SOPS_VERSION=v3.5.0
- SOPS_CHECKSUM=610fca9687d1326ef2e1a66699a740f5dbd5ac8130190275959da737ec52f096
+ SOPS_VERSION=v3.6.0
+ SOPS_CHECKSUM=280ca39d21e6740dfa5332b12ef41698acf014e5f277c5c296c61e83b4ccad21
```

**Comment by ekristen** [comment]
Maybe, not even sure why the SOPS binary is installed the SOPS implementation is golang. 

It does not resolve #3186 though :(

**Comment by via-jordan-sokolic** [comment]
Oh, that's very weird. We are not experiencing that issue, probably because we are not relying on the library but rather the binary version of SOPS.
We're using a wrapper script to find and decrypt all SOPS secrets _before_ running kustomize to template out all our YAMLs. This method is working quite well.

**Comment by stefanprodan** [comment]
Included in #3248

**Pull request closed without merging**
