### PR TITLE
Deleted resources in sync events

### PR DESCRIPTION
**Pull request by ordovicia**
This PR adds `DeletedWorkloadIDs` field to `Event` struct and populates this field with a list of deleted resource IDs for sync events.
Event receivers such as [fluxcloud](https://github.com/justinbarrick/fluxcloud) will be able to know what resources are deleted by Flux.

This PR introduces a breaking change because it adds a field to events.
Event receivers that assumes the current event structure may behave unintentionally.

### CODE REVIEW

**Comment by ordovicia** [comment]
This PR also fixes `compareResources()`. It incorrectly recognized a resource as updated that raised an error during apply.

**Comment by dan-slinky-ckpd** [comment]
@squaremo Do you have some time to give this a review? It would be a useful addition to have as it provides users with better visability on changes to their Kubernetes resources.

**Comment by austinbv** [comment]
Any way we can add a support to see this reviewed and merged - it would make slack notifications for multi-tenet repos much less noisy

**Comment by kingdonb** [comment]
The branch requirements have changed and there is a DCO required now.

If you are still interested in merging this, please `git pull --rebase` and resolve any conflicts, then `git commit --amend -s` to add the sign-off that DCO-bot will require.

Thanks for making this contribution!

**Comment by ordovicia** [comment]
@kingdonb Thank you for your comment. I no longer need this PR to be merged. Closing.

**Pull request closed without merging**
