### PR TITLE
Add metrics on ignored resources.

### PR DESCRIPTION
**Pull request by bmcustodio**
Thought it might be a good idea to add a metric that keeps track of whether a given resource is currently being ignored. The main use-case would be to trigger alerts based on whether any resources are currently being ignored.

### CODE REVIEW

**Comment by bmcstdio** [comment]
Not sure why the tests are failing 🤔

**Comment by bmcstdio** [comment]
@stefanprodan do you think you could have a look please?

**Comment by floriankoch** [comment]
Any chance to get this in?

**Comment by kingdonb** [comment]
Thank you for your contribution. Flux v1 is in maintenance mode and is no longer adding new features unless they are critical.

If this change is still important to you, then we can review it once again, however the expected reasons why changes can be merged to Flux v1 now that it is in maintenance mode are limited to security and maintenance concerns as well as bug fixes.

As some time has passed since this was submitted, and the CI has been updated to include a DCO check, it cannot anymore be considered for merge without a still-interested contributor and a DCO sign-off. This looks like a fairly innocent and non-breaking change, I will leave it open for now as I would consider it as a possibly mergeable change for a next release. But if you have already moved on to Flux v2, then there is probably no point in merging this as we prefer for new features to be added in Flux v2; support for this idea might already have been added there.

Please rebase against the master branch and sign-off your commits to satisfy the DCO bot, or we can close this if you've already moved on. Thanks again.

**Comment by kingdonb** [comment]
Hi, I will reopen if you can signoff with DCO and rebase, but without the DCO bot approval I cannot merge it.

I will reopen if you are still hoping to get this merged, but I haven't heard back since my last message. (If you've already moved on to Flux v2, great!)

**Pull request closed without merging**
