### PR TITLE
whitelist two environment variables for AWS IAM roles in Kubernetes

### LINKED ISSUE #2895: Let Flux fetch dynamic codecommit credentials
**Describe the feature**
At the moment you need to give Flux GIT credentials to access your repository. With rolling keys this isn't possible. It would be a nice feature to have if you can setup Flux to use the attached instance role. This way you can use Flux with Codecommit without the need of having an IAM users.

**What would the new user story look like?**
1. User defines through a parameter to use the IAM role of an instance, user can also define the cache time of these credentials
2. Flux will use these credentials to execute `[aws codecommit credential-helper get !@](https://docs.aws.amazon.com/cli/latest/reference/codecommit/credential-helper/get.html)` and get a temporary access key.
3. Flux uses these keys to write/read from the codecommit repository.

**Expected behavior**
Flux will be able to completely use codecommit repositories alongside other providers.

### PR DESCRIPTION
**Pull request by mattwillsher**
* AWS_WEB_IDENTITY_TOKEN_FILE
* AWS_ROLE_ARN

Such that the AWS CodeCommit git credential helper can be used in the fluxcd container so that static git credentials are not needed. This does require additional components in the fluxcd container. For example:

```
FROM fluxcd/flux:1.20.0

ARG PY3PIP_VERSION=20.1.1-r0
ARG AWSCLI_VERSION=1.18.55-r0
ARG GITREMOTECODECOMMIT_VERSION=1.13

RUN /sbin/apk add --no-cache py3-pip="$PY3PIP_VERSION" aws-cli="$AWSCLI_VERSION"
RUN pip3 install git-remote-codecommit=="$GITREMOTECODECOMMIT_VERSION"
RUN git config --global credential.helper '!aws codecommit credential-helper $@' \
    && git config --global credential.UseHttpPath true
```

An IAM role for the service account can then be used to authentication to CodeCommit (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), with `--git-url` set to the HTTPS URL of the CodeCommit repo as given by aws, and a patch to the flux ServiceAccount giving the IAM role ARN:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: flux
  name: flux
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/MyFluxRole
```

This goes someway to address #2895

### CODE REVIEW

**Comment by jamesinc** [comment]
Keen for this PR to be merged

**Comment by kingdonb** [comment]
This sounds like an important feature, for AWS CodeCommit users 👍

**Comment by kingdonb** [comment]
I'd like to consider including this in the next release, but there are some CI checks which are still marked as failing.

@mattwillsher can you rebase this and add signoff according to instructions that the DCO merge check will provide? (Basically just `git commit -s` or `git commit --amend -s` if you want to skip a step, you can rebase and sign off.)

If you are still interested in merging this, the rebase update should trigger CI to run again. I will add it to the 1.21.3 milestone for now. Thanks.

**Comment by kingdonb** [comment]
Hi,

I want to include this in the next release, but I don't use AWS CodeCommit and can't test it by myself

Also, the DCO bot won't let me merge it if it isn't rebased, and signed-off

Would you be willing to rebase and amend the commit with `--sign-off`?

**Comment by mattwillsher** [comment]
> Would you be willing to rebase and amend the commit with `--sign-off`?

Done

**Comment by kingdonb** [comment]
I will rebase this into a release branch later, and update this PR with the final status when it gets merged in 1.22.0.

👍 thanks for your contribution!

**Comment by kingdonb** [comment]
I changed the language of this PR to say, from:

> This goes someway to resolve #2895

to:

> This goes someway to address #2895

because the former will close #2895 when this PR is merged, but the language indicates it has other issues blocking #2895

**Review by kingdonb — APPROVED** [review]
LGTM

**Pull request merged**
