### PR TITLE
Adds nodeSelector to deployment templates for mixed OS clusters

### PR DESCRIPTION
**Pull request by rparsonsbb**
Adds an `os` `nodeSelector` to the two deployments required for the eksctl deployment of flux to work correctly.

### CODE REVIEW

**Comment by 2opremio** [comment]
@rparsonsbb thanks for the contribution 🌷 

Can you please:
1. Rebase on top of master
2. Run `make generate-deploy` and commit the result
3. Add the same change to `chart/flux/templates/deployment.yaml`

Thanks!

**Comment by rparsonsbb** [comment]
Sure thing!

**Comment by 2opremio** [comment]
@rparsonsbb please cleanup the history of your branch so that the PR only includes your commits (and no merge commits).

**Comment by rparsonsbb** [comment]
Done!

**Comment by 2opremio** [comment]
@rparsonsbb Great. Did you test that it works when using extra `nodeSelector` and `memcached.nodeSelector` values?

**Comment by rparsonsbb** [comment]
Yes, I generated templates and installed in our dev mixed os cluster with no additional `nodeSelector` values in the `values.yaml` to ensure that both flux and memcached deployments function and to make sure that the nodeSelector object was created properly then added additional values (`kubernetes.io/hostname`, `kubernetes.io/arch`) to validate adding more values.

Below works in long or short yaml notation

### No additional values
`/chart/flux/values.yaml`
> nodeSelector: {}
> memcached.nodeSelector: {}


```
❯helm template ./ | grep -C 5 'nodeSelector'
...
          - --registry-trace=false
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
      nodeSelector: 
        beta.kubernetes.io/os: linux
---
# Source: flux/templates/memcached.yaml
apiVersion: apps/v1
kind: Deployment
--
          {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 11211
          runAsUser: 11211
      nodeSelector:
        beta.kubernetes.io/os: linux
```

### One additonal value
 `/chart/flux/values.yaml`
> nodeSelector: {kubernetes.io/host: bb-dev-01-linux-ng-1}
> memcached.nodeSelector: {kubernetes.io/host: bb-dev-01-linux-ng-2}
```
❯helm template ./ | grep -C 5 'nodeSelector'
...
          - --registry-trace=false
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
      nodeSelector: 
        beta.kubernetes.io/os: linux
        kubernetes.io/host: bb-dev-01-linux-ng-1
---
# Source: flux/templates/memcached.yaml
apiVersion: apps/v1
--
          {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 11211
          runAsUser: 11211
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/host: bb-dev-01-linux-ng-2
```

### Multiple additonal values
 `/chart/flux/values.yaml`
> nodeSelector: {kubernetes.io/host: bb-dev-01-linux-ng-1, disk: ssd}
> memcached.nodeSelector: {kubernetes.io/host: bb-dev-01-linux-ng-2, disk: ssd}
```
❯helm template ./ | grep -C 5 'nodeSelector'
...
          - --registry-trace=false
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
      nodeSelector: 
        beta.kubernetes.io/os: linux
        kubernetes.io/host: bb-dev-01-linux-ng-1
        disk: ssd
---
# Source: flux/templates/memcached.yaml
apiVersion: apps/v1
--
          {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 11211
          runAsUser: 11211
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/host: bb-dev-01-linux-ng-2
        disk: ssd
```

**Comment by 2opremio** [comment]
Great, thanks!

**Pull request merged**
