### PR TITLE
[WIP] Explain what's need to use a git repo over HTTPS

### PR DESCRIPTION
**Pull request by squaremo**
(needs more exploration to tighten up the instructions, and probably links or paras in other docs)

### CODE REVIEW

**Comment by songsak2299** [comment]
Ko

**Comment by squaremo** [comment]
I tried IRL to set things up so I could use an HTTPS git URL, and it is not quite as simple as I've indicated here. To be clear, this isn't wrong -- it's just not enough information to get it working easily. In particular, you need to tell git to use a credentials store, then mount that as well. It is infuriatingly fiddly to get it right, and computerproof instructions are called for.

**Comment by squaremo** [comment]
(marking as blocked as a reminder that it needs more work)

**Comment by squaremo** [comment]
Closing this as I'm not expecting to complete it any time soon.

**Pull request closed without merging**
