### PR TITLE
Introduce advanced templating for use as subchart

### PR DESCRIPTION
**Pull request by MaxRink**
This introduces advanced templating that allowsyou to easier use the Flux chart as a subchart in another helm v2 Chart.
This shouldn't break anything as tpl already is a supported feature with Helm 2.
It adds the benefit that the usage of flux as a subcharts becomes easier as you can now reference global values within your values.yaml, thus you dont need to define the same value multiple times and can just crossreference it.
Example:

```yaml
global:
  tenant:
    name: tenant_1
    environment: packet
    git: "git.example.com"
    token: "somethingCryptic"
    clustername: "workload-cluster-1"

flux:
  git:
    url: https://x-access-token:{{ .Values.global.tenant.token }}@{{ .Values.global.tenant.git }}/schiff/platform/infrastructure/alpha3-environments.git
    branch: "master"
    path: "platform/tenantClusterComponents/{{ .Values.global.tenant.environment }}/{{ .Values.global.tenant.name }}/{{ .Values.global.tenant.clustername }}/core-components"
    user: "{{ .Values.global.tenant.clustername }}-flux"
    email: "{{ .Values.global.tenant.clustername }}-flux@clusters.das-schiff.telekom.de"
```
Addendum:
imo it doesnt make sense to introduce this to every option, as you propably wont overwrite many of the values from your umbrella chart. This PR basically just introduces what /we/ needed, but im sure that there are other values where it also would make sense to switch to this style.

### CODE REVIEW

**Comment by MaxRink** [comment]
In what section would you see the documentation?
In the README and values.yaml or just in one of them?

**Comment by hiddeco** [comment]
@MaxRink `README.md` of the chart would be the best place I think.

**Comment by MaxRink** [comment]
I've added my initial draft of docs for this feature and actually found a few more Variables that are propably woth handeling in this mannor, like HostAliases.
I'll addd them to this PR once i find time to write the necassesary helper code for nested lists.

**Comment by kingdonb** [comment]
Thank you for your contribution. Flux v1 is in maintenance mode and is no longer adding new features unless they are critical.

I have seen Flux used in Umbrella charts, like in this example: https://github.com/okteto/charts/tree/master/flux

I think that means this change is not needed, but it's possible there is something I have misunderstood about this.

If this change is still important to you, then we can review it once again, however the expected reasons why changes can be merged to Flux v1 now that it is in maintenance mode are limited to security and maintenance concerns as well as bug fixes.

As some time has passed since this was submitted and there has been no follow-up for a while, I think it's safer to close.

**Pull request closed without merging**
