### PR TITLE
Store public key in k8s secret

### PR DESCRIPTION
**Pull request by alaa**
This PR is a clone of the old #2916 for the reason that the upstream fork of the #2916 was deleted therefore opening this new PR.
For more details about the purpose of this change, please check the conversation here: https://github.com/fluxcd/flux/pull/2916

### CODE REVIEW

**Comment by alaa** [comment]
Hi @kingdonb, just a friendly reminder.

**Comment by kingdonb** [comment]
Thanks, this looks straightforward and I don't think it has any potential to cause harm or break things.

I will see that it gets included in the reviews for 1.22.0, which should be coming out this week. 🙌

**Comment by kingdonb** [comment]
I rebased this to include it in the omnibus branch that I've composed for Flux v1.22.0 release.

**Review by kingdonb — APPROVED** [review]
LGTM 👍

**Pull request merged**
