### PR TITLE
Add fluxd flag to set klog verbosity

### PR DESCRIPTION
**Pull request by stefanprodan**
Fix: #2407

### CODE REVIEW

**Comment by cristian-radu** [comment]
I just gave this a quick try by building cristianradu/flux:klog with 

```
	// Explicitly initialize klog to enable stderr logging,
	// and parse our own flags.
	klogFlags := flag.NewFlagSet("klog", flag.ExitOnError)
	klog.InitFlags(klogFlags)
	verbosity := klogFlags.Lookup("v")
	verbosity.Value.Set(strconv.Itoa(*k8sVerbosity))

	klog.V(0).Infoln("klog level 0 message")
	klog.V(4).Infoln("klog level 4 message")
```

and running it with --k8s-verbosity=4

```
I0828 14:33:24.506799       6 main.go:211] klog level 0 message
Flag --registry-poll-interval has been deprecated, changed to --automation-interval, use that instead
ts=2019-08-28T14:33:24.506856362Z caller=main.go:241 version=klog-verbosity-63449f19-wip
ts=2019-08-28T14:33:24.506878212Z caller=main.go:370 msg="using in cluster config to connect to the cluster"
```
 and I only got the level 0 message printed out :(

**Comment by stefanprodan** [comment]
Ah I tested it by setting the default value to 4. I’ll fix it when I get home, the setter should be used after parse flags.

**Comment by stefanprodan** [comment]
@cristian-radu please give it a try, it should work.

**Comment by cristian-radu** [comment]
yep, it works now :+1:

**Pull request merged**
