### PR TITLE
add dockerfile for build a Debian based image

### PR DESCRIPTION
**Pull request by maurorappa**
I create a debian based image with the bare minimum set of changes to make it work.
you may need for K8s strategic merge patching as I did.

### CODE REVIEW

**Comment by kingdonb** [comment]
Thanks for contributing this! I am not sure it can be merged, as people may assume it is a supported mode, but for anyone that prefers to use a Debian base, this could come in handy.

If you still want to merge it, you can rebase and follow the instructions for DCO. Otherwise I will recommend closing this without merge, since Flux v1 is in maintenance mode and not likely to change base distributions from Alpine at this point.

**Comment by maurorappa** [comment]
it's fine, bye!

**Comment by AntonDobshikov** [comment]
seems that's not so easy
```root@225586d6ac7c:/home/flux# kubeyaml
bash: /usr/lib/kubeyaml/kubeyaml: No such file or directory
root@225586d6ac7c:/home/flux# cd /usr/lib/kubeyaml/
root@225586d6ac7c:/usr/lib/kubeyaml# ldd kubeyaml
        linux-vdso.so.1 (0x00007ffee63e5000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f292dfa8000)
        libc.musl-x86_64.so.1 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f292dde7000)
        /lib/ld-musl-x86_64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f292e1e7000)
root@225586d6ac7c:/usr/lib/kubeyaml#```

**Comment by AntonDobshikov** [comment]
And after
https://github.com/alexander-akhmetov/python-telegram/issues/3
```
root@225586d6ac7c:/usr/lib/kubeyaml# kubeyaml
Error loading shared library libz.so.1: No such file or directory (needed by /usr/lib/kubeyaml/kubeyaml)
Error relocating /usr/lib/kubeyaml/kubeyaml: zlibVersion: symbol not found
Error relocating /usr/lib/kubeyaml/kubeyaml: inflate: symbol not found
Error relocating /usr/lib/kubeyaml/kubeyaml: inflateInit_: symbol not found
Error relocating /usr/lib/kubeyaml/kubeyaml: inflateEnd: symbol not found

**Pull request closed without merging**
