### PR TITLE
Add Carrot to users list

### PR DESCRIPTION
**Pull request by austinpray**
- Adds [Carrot](https://carrot.com) to the users list 🎉
- Shifts and sorts list

### CODE REVIEW

**Comment by austinpray** [comment]
@hiddeco Oops, I see where the conflict is. Fixing

**Review by hiddeco — APPROVED** [review]
Thank you very much @austinpray :carrot:

**Comment by austinpray** [comment]
(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧:carrot:

**Pull request merged**
