### PR TITLE
Run `go mod tidy`

### PR DESCRIPTION
**Pull request by 2opremio**
Maybe we should do something to do this automatically (or at least make sure PR creators do it).

Maybe piggyback on `make check-generated`?

### CODE REVIEW

**Comment by stefanprodan** [comment]
Hmm what about go.sum? I see the Kubernetes code-gen in there

**Comment by hiddeco** [comment]
Isn't this the result of Go Mod operations on `/pkg/install` and `/` fighting each other?

**Comment by squaremo** [comment]
All invocations of go build (or test, or probably other things) should use `-mod=readonly`, so that they will fail if go would otherwise modify go.{mod,sum}.

I attempted to make this the case a while ago, but the code generation in pkg/install got in the way. It may be feasible now.

**Comment by squaremo** [comment]
> Isn't this the result of Go Mod operations on `/pkg/install` and `/` fighting each other?

It should not be -- those operate independently.

**Comment by 2opremio** [comment]
> Hmm what about go.sum? I see the Kubernetes code-gen in there

God point, but I don't know the answer. That's what `go mod tidy` did.

**Comment by 2opremio** [comment]
> All invocations of go build (or test, or probably other things) should use `-mod=readonly`, so that they will fail if go would otherwise modify go.{mod,sum}.

You mean in CI, right? But then ... how do you fill the cache in?

**Comment by squaremo** [comment]
> how do you fill the cache in?

`go` will still fetch things it doesn't have.

**Comment by 2opremio** [comment]
> You mean in CI, right? But then ... how do you fill the cache in?

I completely misunderstood how `-mod=readonly` works sorry.

That won't work for all cases (this case in particular), because building doesn't lead to the `go.mod` changes in this PR, only `go mod tidy` does.

**Comment by squaremo** [comment]
> That won't work for all cases (this case in particular), because building doesn't lead to the `go.mod` changes in this PR, only `go mod tidy` does.

No, but it'll force people to be conscious of adding dependencies, so they might get in the habit of running `go mod tidy` when things change :-)

**Comment by 2opremio** [comment]
can we merge this though? :)

**Comment by stefanprodan** [comment]
I think we can run `tidy` after the code gen check and fail the build if go.mod or sum changes. We can show a message in CI like "please run go mod tidy".

**Comment by 2opremio** [comment]
> I think we can run `tidy` after the code gen check and fail the build if go.mod or sum changes. We can show a message in CI like "please run go mod tidy".

Yeah, that's what I had in mind. I will do it in a separate PR.

**Pull request merged**
