### PR TITLE
Upgrade to kubectl 1.17.12

### PR DESCRIPTION
**Pull request by dabeck**
This PR updates kubectl to 1.17.12

kubectl versions with patch versions lower than v1.18.8 v1.17.11 or v1.16.14 have issues updating CRD files, due to [a bug when handling deeply nested CRDs](https://github.com/kubernetes/kubernetes/issues/91615). This bug will make kubectl apply -f [...] hang.
Ref: https://cert-manager.io/docs/installation/upgrading/upgrading-0.15-0.16/

### CODE REVIEW

**Comment by stefanprodan** [comment]
@dabeck can you please bump it to the latest v1.18, thanks

**Comment by dabeck** [comment]
> @dabeck can you please bump it to the latest v1.18, thanks

Sure, I thought v1.17. was a thing in this project.

**Comment by stefanprodan** [comment]
Kubernetes 1.19 is out, our policy is to keep up with upstream and bump kubectl and packages to latest minor - 1

**Comment by dabeck** [comment]
> Kubernetes 1.19 is out, our policy is to keep up with upstream and bump kubectl and packages to latest minor - 1

I had a quick try updating to k8s 1.18 but this breaks a lot of other dependencies as well. Sadly I dad no time to have a deeper look.

**Comment by squaremo** [comment]
kubectl was updated to 1.18.9 in #3309. I think this will fix the particular problem of updating CRD files, @dabeck. We may have to stick with _packages_ from 1.17 for now, as noted in #3309. I'm going to close this PR, since it's probably not possible to make progress, and the substantive issue is fixed (and release in 1.21.0). Thanks!

**Pull request closed without merging**
