### PR TITLE
Add new metric to check if the repository is down or misconfigured

### PR DESCRIPTION
**Pull request by drazul**
This Pull Request add a new metric named flux_git_ready.

This new metric can be used to configure an alert when the repository is down or is misconfigured (or any other git error that makes flux mark the repository as not ready).

### CODE REVIEW

**Review by swade1987 — APPROVED** [review]

**Comment by kingdonb** [comment]
@drazul Are you still interested in merging this? If you run `git pull --rebase origin master` and `git push --force drazul master` it should trigger CI to run again.

The DCO bot has been added to merge checks since this was submitted, if you perform the rebase it should trigger CI once again and the DCO bot will add a link explaining how to sign off your contribution.

I am adding this to v1.21.3 milestone since I am not sure if you are still interested in merging it, we will do 1.21.2 imminently for a docs update and this can be discussed then for including in the next release, if you want.

**Comment by drazul** [comment]
@kingdonb I just rebased the code to add this change and all checks have been passed.

Sorry for the delay.

**Comment by kingdonb** [comment]
Thanks, I will visit this again when preparing for the next milestone release. It may be some time, I want to make a noticeable dent in the open issues on Flux v1 (seriously, like 25-50% or more closed or pending closing) before attempting another release.

It appears I can now update your branch with newly minted write access powers I have, as long as there isn't a conflict shown (which it appears there isn't.) I'm going to try that out now 👍

**Comment by kingdonb** [comment]
Rebasing this to include it in #3442 👍

**Review by kingdonb — APPROVED** [review]
LGTM

**Pull request merged**
