### PR TITLE
Add NetHunt to the list of companies using Flux in production.

### PR DESCRIPTION
**Pull request by SvitlanaTsupryk-jul18**
Add NetHunt to the list of companies using Flux in production.

### CODE REVIEW

**Comment by dholbach** [comment]
Can you sign your commit? https://github.com/fluxcd/flux/pull/3390/checks?check_run_id=1629675492

**Comment by dholbach** [comment]
And thanks for your PR and being part of the Flux community!

**Review by blaquezzz — APPROVED** [review]

**Comment by SvitlanaTsupryk-jul18** [comment]
Thank you for your product!
I have written from my local brunch:
git commit --amend --signoff
And I saw a file, but it wasn`t closed by editor. After running:
git push --force-with-lease origin adding-to-flux-list
it was written :'Everything up-to date'
What else should I do?
Thank you)

**Comment by dholbach** [comment]
Did you safe the file?

**Comment by SvitlanaTsupryk-jul18** [comment]
Thanks!

**Comment by SvitlanaTsupryk-jul18** [comment]
But it still doesn`t pass DCO. 
Should I do this all again?

**Pull request closed without merging**
