### PR TITLE
Install docs fixes

### PR DESCRIPTION
**Pull request by stefanprodan**
Fix fluxctl install command, replace `--git-path` with `--git-paths`.
Fix podinfo example, replace `PODINFO_UI_COLOR`  with `PODINFO_UI_MESSAGE`.
Fix Kustomize install, add `namespace.yaml` to resources.

### CODE REVIEW

**Comment by stefanprodan** [comment]
@hiddeco can we pin the `stable` to a master commit instead of tag? The current fluxctl install command is broken 😢

**Comment by hiddeco** [comment]
@stefanprodan not possible, `stable` is magic from RTD based on published semver (git) tags.

**Comment by stefanprodan** [comment]
I would switch back to master then...

**Comment by 2opremio** [comment]
> Fix fluxctl install command, replace `--git-path` with `--git-paths`.

Oh dear. It sucks that it's inconsistent with `fluxd`, sorry about that. Since it's already released, should we simply accept both?

**Comment by stefanprodan** [comment]
@2opremio yes I think accepting both would be best.

**Pull request merged**
