### PR TITLE
Add envsubst package to docker image

### PR DESCRIPTION
**Pull request by stevehipwell**
This PR adds the `envsubst` command to the _Docker_ image to enable automation users to work around the limitations (by design) of `kustomize`.

This resolves https://github.com/fluxcd/flux/issues/3138.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@kingdonb this replaces PR https://github.com/fluxcd/flux/pull/3216 as I'd removed my original fork.

**Comment by stefanprodan** [comment]
@stevehipwell can you please comment on this RFC for Flux2, looking forward to your opinion https://github.com/fluxcd/kustomize-controller/pull/253

**Comment by stevehipwell** [comment]
@stefanprodan what is the status of this PR?

**Comment by kingdonb** [comment]
@stevehipwell I am putting together a list of PRs to include in the 1.21.2 release, would you like to have this merged for that upcoming release?

**Comment by kingdonb** [comment]
I don't know if it's appropriate to include a new feature in a point release, but if this is still needed we can add a flux 1.22.0 milestone and prioritize including it there. For those who may be stuck using Flux v1 for a time while it is still in maintenance mode, we want to make the transition to Flux v2 as smooth as possible. I think there has been support expressed for merging this in v1 as well.

**Comment by kingdonb** [comment]
Rebasing for inclusion in the merge thru #3442 👍

**Review by kingdonb — APPROVED** [review]
LGTM

**Comment by stevehipwell** [comment]
Thanks @kingdonb. Any idea when the chart for the v1.22.0 release will be created?

**Comment by yebyen** [comment]
Pr #3449 is just approved and will be merged and pushed within about 30 minutes from now.

**Comment by kingdonb** [comment]
```
Release "flux" has been upgraded. Happy Helming!
NAME: flux
LAST DEPLOYED: Wed Mar 17 14:53:47 2021
NAMESPACE: flux
STATUS: deployed
REVISION: 7
...
flux-864d84f776-rpk7f            1/1     Running             0          18s
```

🎉 

Thanks for your help with this release @stevehipwell

**Pull request merged**
