### PR TITLE
Load fluxd arguments from config file

### PR DESCRIPTION
**Pull request by tkeech1**
This PR is addresses [2043](https://github.com/fluxcd/flux/issues/2043). It adds support for a fluxd configuration file that is created as a secret or configmap which is mounted in the fluxd container. This change only supports local config files (no support for Github URLs yet). Command-line arguments override values specified in the config file.

There are two new command line options:

**config.file** - a yaml config file to configure fluxd
**config.asConfigMap** - a boolean value that specifies if the file is loaded as a config map (if false or unspecified, the config file is loaded as a secret)

**Helm:**
For a Helm install, the flux-config.yaml file must be located in the chart/flux directory.

`helm install chart/flux --set helmOperator.create=true --set helmOperator.createCRD=false --set config.file=flux-config.yaml --set config.asConfigMap=true --namespace flux`

**Fluxctl:**
`fluxctl install --config-file=chart/flux/flux-config.yaml --config-as-configmap=false --namespace=flux | kubectl apply -f -`

Changes are not yet documented in the references or guides. Thanks for any feedback.

### CODE REVIEW

**Comment by squaremo** [comment]
Ohhhh, this looks promising! What do you reckon is left to do @tkeech1 ?

**Comment by stefanprodan** [comment]
I think this would be a good moment to introduce a config struct e.g.:

```go
type Config struct {
	GitUrl      string `mapstructure:"git-url"`
	GitBranch   string `mapstructure:"git-branch"`
}

func main() {
	// read file
	viper.ReadInConfig()

	// bind flags 
	viper.BindPFlags(fs)

	// bind environment variables
	viper.SetEnvPrefix("FLUXCD")
	viper.SetEnvKeyReplacer(strings.NewReplacer("-", "_"))
	viper.AutomaticEnv()

	// unmarshal instead of calling viper.GetString for each config field
	var config Config
	viper.Unmarshal(&config)
}
```

**Comment by tkeech1** [comment]
Thanks for the feedback. I added the config struct and updated the documentation. Please let me know if you'd like any other changes.

**Comment by squaremo** [comment]
I started rebasing this, fixed a few things along the way, then realised I had diverged from the PR branch. I'm working here: https://github.com/fluxcd/flux/compare/issue/2043-config-file.

I've preserved the authorship of commits that are substantially similar; we can either consider a PR from that branch, or I can push to this PR (and we don't have to decide right now ..)

**Comment by 2opremio** [comment]
Closing in favor of #2544

**Pull request closed without merging**
